### ISSUE TITLE
Use Dynogels instead of Vogels

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/dynamic-dynamodb#10]
**Context**

We discovered that the `vogels` package has not been maintained recently. The last change merged into the master branch was from 7 months ago (Jan 13, 2016). We submitted a PR to `vogels` to fix a bug we discovered, and are in the belief that it won't be merged any time soon. We already made a [change in our code](https://github.com/screwdriver-cd/datastore-dynamodb/pull/15) to be defensive against this issue.

**Issue**

To use the `dynogels` package instead of the `vogels` package.

There is a forked version called [`dynogels`](https://github.com/clarkie/dynogels) that is currently maintained and is actively merging in PR changes. They already have our previous PR [ported over](https://github.com/clarkie/dynogels/pull/15) to it. From our initial investigation, it also preserves the same API as `vogels`.

**Comment by petey** [comment]
I'm ok with this.
